### ISSUE TITLE
pygame.error: video system not initialized

### ISSUE THREAD

**Issue by svargas93** [ronbal/photobooth#1]
I'm getting an issue when starting.. the intro screen comes up but  but when i when the space bar i get this error.. i have tried inputting my screen size using tvservice

> Traceback
 (most recent call last):
  File "photobooth.py", line 50, in <module>
    monitor_w, monitor_h = pygame.display.Info().current_w, pygame.display.Info().current_h
pygame.error: video system not initialized

sometimes i get this error too 

> pi@raspberrypi:~/photobooth $ sudo python3 photobooth.py
Traceback (most recent call last):
  File "photobooth.py", line 204, in <module>
    starting()
  File "photobooth.py", line 73, in starting
    shoot()
  File "photobooth.py", line 123, in shoot
    countdown_overlay('test')
  File "photobooth.py", line 160, in countdown_overlay
    o = camera.add_overlay(pad.tostring(), size=img.size)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 697, in tostring
    "Please call tobytes() instead.")
NotImplementedError: tostring() has been removed. Please call tobytes() instead.
Goodbye.

**Comment by ronbal** [comment]
hi i have updated the script, please try now again. Photobooth is now compatible with Stretch
